site_name: Geolab
site_description: Geotechnical engineering software for students and professionals.
site_url: https://geolab.github.io
site_author: Patrick Boateng
repo_url: https://github.com/patrickboateng/geolab
repo_name: patrickboateng/geolab

theme:
    name: "material"
    icon:
        repo: fontawesome/brands/github
    features:
        - search
        - search.highlight
        - search.suggest
        - navigation.footer
    palette:
        # Palette toggle for light mode
        - scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        # Palette toggle for dark mode
        - scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

plugins:
    - search:
          lang: en
    - mkdocstrings

markdown_extensions:
    - toc:
          toc_depth: 6

    - markdown_include.include:
          base_path: docs
          throwException: true

    - pymdownx.arithmatex:
          generic: true

    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/patrickboateng/geolab

        - icon: fontawesome/brands/linkedin
          link: https://linkedin.com/in/patrickboateng
nav:
    - Getting Started with GeoLab: index.md
    - tutorials.md
    - how-to-guides.md
    - reference.md
    - explanation.md
    - Topics:
          - Soil Classification: soil_classification.md

copyright: Copyright &copy; 2023 geolab
