[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "geolab"
version = "0.1.0"
authors = [{name="Patrick Boateng", email="boatengpato.pb@gmail.com"}]
description = ""
readme = "README.md"
license = { file = "LICENSE.txt" }
requires-python = ">=3.10"
dependencies = []
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "Programming Language :: Python :: Implementation :: CPython",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Developers",
]

[project.urls]
"Homepage" = "https://github.com/patrickboateng/geolab"

[tool.setuptools]
packages = ["geolab"]

[project.optional-dependencies]
dev = ["wheel", "black", "pytest", "mypy"]

[tool.pytest.ini_options]
addopts = "-ra --verbose --color=auto --code-highlight=yes --strict-markers"
minversion = "6.0"
testpaths = ["tests"]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true

[tool.docformatter]
style = "sphinx"
black = true
wrap-summaries = 79
wrap-descriptions = 79
pre-summary-newline = true
make-summary-multi-line = true
close-quotes-on-newline = true

[tool.pydocstyle]
# convention = "pep257"
ignore = ["D107", "D200"]