[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-ra --verbose --color=auto --code-highlight=yes --strict-markers"
minversion = "6.0"
testpaths = ["tests"]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true

# [tool.docformatter]
# recursive = true
# wrap-summaries = 82
# wrap-descriptions = 81
# blank = true
