[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-ra --verbose --color=auto --code-highlight=yes --strict-markers"
minversion = "6.0"
testpaths = ["tests"]